### ISSUE TITLE
the script needs to be customized to replace "USER" with your own username?

### ISSUE THREAD

**Issue by docteurklein** [FernandoMiguel/sshremotekeys#1]
It seems your script hardcode the username `USER`, and that seems quite dangerous given you don't really state it in the docs that you should **absolutely** customize it.

I guess there is a better solution, which is to use the first argument passed to the script when sshd invokes the command:

```
     AuthorizedKeysCommand
             Specifies a program to be used to look up the user's public keys.  The program must be
             owned by root, not writable by group or others and specified by an absolute path.  Argu‐
             ments to AuthorizedKeysCommand accept the tokens described in the TOKENS section.  If no
             arguments are specified then the username of the target user is used.
```

**Comment by FernandoMiguel** [comment]
You are correct, particularly since gh/user exists.
We don't want people accidently granting access to their infrastructure to 3rd parties.
I'll make the documentation clearer and change the url.

A PR would be appreciated too

**Comment by FernandoMiguel** [comment]
some initial fix with https://github.com/FernandoMiguel/sshremotekeys/commit/304dd50ef39abfd9d0aad78542a4f686a1eba1ad

**Comment by FernandoMiguel** [comment]
I don't see a usecase where the url(s) is passed as a parameter.
I've added some protection and further instructions.

https://github.com/FernandoMiguel/sshremotekeys/commit/0bd22affd688cf08c1821c233bb55f5a33bc23e5 closes this
