### ISSUE TITLE
Cache for rate limits

### ISSUE THREAD

**Issue by Slamdunk** [FernandoMiguel/sshremotekeys#2]
I'm not aware of average key rotation time of the user this package is written for, but I would consider acceptable to cache my keys for, let's say, 5 minutes, without compromizing security in case of key revocation.

Back from easter vacation I can PR a change, if you haven't written something yet.

**Comment by FernandoMiguel** [comment]
You mean for the curl?
GitHub has a cache control header of no-cache.
Writing them to disk woul stil require to check etag against the server, or a clean up task.

Neither good to implement, but I'm open to discussion

**Comment by Slamdunk** [comment]
I mean cache, and query only the cache till it's valid.

1. Check for cache saved to a file
1. If non existent, get the cURL, save it to file and use it
1. If existent, check `stat -c %Y` result
1. If below `date +%s` minus 5 minutes, go to [2], otherwise use cache result

No external request within 5 minutes validity.

**Comment by FernandoMiguel** [comment]
something along the lines of 
expr \`date +%s\` - \`stat -c %Y /PATH/SOMEFILE\`

might work. we still would have to deal with multiples groups of users in case they exist not to overwrite this file.
I'll be waiting for your PR. 
Ta
